services:
  postgres:
    image: postgres:16-alpine
    container_name: loan-db
    environment:
      POSTGRES_DB: loan_management
      POSTGRES_USER: loan_user
      POSTGRES_PASSWORD: loan_secret
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loan_user -d loan_management"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
